---
abstract: 'Apache Kafka low-level synchronous API, which does not use Zookeeper.'
author:
  - 'Sergey Gladkov'
build_requires:
  Capture::Tiny: '0.24'
  Carp: '1.08'
  Clone: '0.36'
  Config::IniFiles: '2.83'
  Const::Fast: '0.014'
  Cwd: '3.2501'
  Data::Dumper: 2.121_14
  Exporter: '5.62'
  File::HomeDir: '1.00'
  File::Path: '2.04'
  File::Spec: '3.2501'
  File::Spec::Functions: '3.2501'
  IO::File: '1.14'
  IO::Socket::INET: '1.31'
  IO::Socket::IP: '0.37'
  List::Util: '1.19'
  Net::EmptyPort: '0'
  Params::Util: '1.07'
  Proc::Daemon: '0.14'
  Proc::ProcessTable: '0.51'
  Scalar::Util: '1.19'
  Scalar::Util::Numeric: '0.22'
  Socket: '1.80'
  Sub::Install: '0.927'
  Sys::SigAction: '0.21'
  Test::Deep: '0.119'
  Test::Dist::VersionSync: '0'
  Test::Distribution: '0'
  Test::EOL: '0'
  Test::Exception: '0.32'
  Test::Fixme: '0'
  Test::Kwalitee: '0'
  Test::Kwalitee::Extra: '0'
  Test::MinimumVersion: '0'
  Test::Mojibake: '0'
  Test::More: '0.72'
  Test::NoTabs: '0'
  Test::NoWarnings: '1.04'
  Test::Perl::Critic: '0'
  Test::PureASCII: '0'
  Test::Spelling: '0'
  Test::Strict: '0'
  Test::Synopsis: '0'
  Test::TCP: '2.08'
  Test::Vars: '0'
  Test::Version: '0'
  Time::HiRes: '1.9711'
  Try::Tiny: '0.21'
  perl: '5.010'
configure_requires:
  Module::Build::Tiny: '0.034'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.20, Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kafka
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Kafka:
    file: lib/Kafka.pm
    version: '1.08'
  Kafka::Connection:
    file: lib/Kafka/Connection.pm
    version: '1.08'
  Kafka::Consumer:
    file: lib/Kafka/Consumer.pm
    version: '1.08'
  Kafka::Exceptions:
    file: lib/Kafka/Exceptions.pm
    version: '1.08'
  Kafka::IO:
    file: lib/Kafka/IO.pm
    version: '1.08'
  Kafka::IO::Async:
    file: lib/Kafka/IO/Async.pm
    version: '1.08'
  Kafka::Int64:
    file: lib/Kafka/Int64.pm
    version: '1.08'
  Kafka::Internals:
    file: lib/Kafka/Internals.pm
    version: '1.08'
  Kafka::Message:
    file: lib/Kafka/Message.pm
    version: '1.08'
  Kafka::Producer:
    file: lib/Kafka/Producer.pm
    version: '1.08'
  Kafka::Protocol:
    file: lib/Kafka/Protocol.pm
    version: '1.08'
requires:
  AnyEvent: '7.17'
  Authen::SCRAM: '0'
  Carp: '1.08'
  Compress::LZ4Frame: '0.012001'
  Compress::Snappy: '0.23'
  Const::Fast: '0.014'
  Data::Compare: '1.24'
  Data::HexDump::Range: '0'
  Data::Validate::Domain: '0.11'
  Data::Validate::IP: '0.24'
  Exception::Class: '1.37'
  Exporter: '5.62'
  Gzip::Faster: '0.19'
  IO::Select: '1.17'
  List::Util: '1.19'
  Params::Util: '1.07'
  Scalar::Util: '1.19'
  Scalar::Util::Numeric: '0.22'
  Socket: '1.80'
  String::CRC32: '1.5'
  Sys::SigAction: '0.21'
  Time::HiRes: '1.9711'
  Try::Tiny: '0.21'
  perl: '5.010'
resources:
  bugtracker: https://github.com/TrackingSoft/Kafka/issues
  homepage: https://github.com/TrackingSoft/Kafka
  repository: https://github.com/TrackingSoft/Kafka.git
version: '1.08'
